### ISSUE TITLE
Crash when range is invalid

### ISSUE THREAD

**Issue by totebo** [selimanac/defold-random#2]
Would it be possible to throw an error for code like this? 

`rnd.range(1,0)`

Currently it produces a hard crash with no error trace.

**Comment by selimanac** [comment]
Yes, it is possible. I'm trying to avoid comparing numbers as much as I can because of the performance concerns. It is actually simple. You can fork and add this easily by adding;`if min > max ... assert()`... https://github.com/selimanac/defold-random/blob/d591df6b7b658a630b36eb895fcf0ff7925694c9/pcgrandom/src/pcgrandom.cpp#L69

**Comment by totebo** [comment]
That's a good enough reason for me. I could wrap it in Lua and do the checks there if needed.
